user.h: Added equality, assignment, and insertion operators
Added equality, assignment and insertion operators for loading and saving user databases.
Added a private copy function alongside a copy constructor.
Added default parameters to constructor (needed to avoid compiler error C2512)